// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ColumnarForm: typeof import('./src/components/echarts/columnarForm.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HistoryNav: typeof import('./src/components/common/HistoryNav.vue')['default']
    InfluenceForm: typeof import('./src/components/echarts/influenceForm.vue')['default']
    InputRecommend: typeof import('./src/components/common/search/InputRecommend.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Price_moventment: typeof import('./src/components/echarts/price_moventment.vue')['default']
    PriceMove: typeof import('./src/components/echarts/priceMove.vue')['default']
    ProductDateShow: typeof import('./src/components/content/productDateShow.vue')['default']
    ResultProduct: typeof import('./src/components/common/search/ResultProduct.vue')['default']
    SearchDialog: typeof import('./src/components/common/search/SearchDialog.vue')['default']
    SearchProduct: typeof import('./src/components/common/search/SearchProduct.vue')['default']
    StartSearch: typeof import('./src/components/content/StartSearch.vue')['default']
  }
}

export { }
